export const UNIT_DESIGNATORS: Readonly<Record<string, string>> = {
  TOWER: "TOWER",
  TWR: "TOWER",
  "#": "#",
  APARTMENT: "APT",
  PMB: "PMB",
  APT: "APT",
  BLDG: "BLDG",
  BASEMENT: "BSMT",
  BSMT: "BSMT",
  BUILDING: "BLDG",
  DEPARTMENT: "DEPT",
  DEPT: "DEPT",
  FL: "FL",
  FLR: "FL",
  FLOOR: "FL",
  FRNT: "FRNT",
  FRONT: "FRNT",
  HANGAR: "HNGR",
  HANGER: "HNGR",
  HNGR: "HNGR",
  KEY: "KEY",
  LBBY: "LBBY",
  LOBBY: "LBBY",
  LOT: "LOT",
  LOWER: "LOWR",
  LOWR: "LOWR",
  OFC: "OFC",
  OFFICE: "OFC",
  PENTHOUSE: "PH",
  PH: "PH",
  PIER: "PIER",
  REAR: "REAR",
  RM: "RM",
  ROOM: "RM",
  SIDE: "SIDE",
  SLIP: "SLIP",
  SPACE: "SPC",
  SPC: "SPC",
  SP: "SPC",
  STE: "STE",
  STOP: "STOP",
  SUITE: "STE",
  TRAILER: "TRLR",
  TRLR: "TRLR",
  UNIT: "UNIT",
  UPPER: "UPPR",
  UPPR: "UPPR",
};

export const UNIT_DESIGNATORS_WITHOUT_NUMBER = new Set([
  "BSMT",
  "FRNT",
  "LBBY",
  "LOWR",
  "OFC",
  "PH",
  "REAR",
  "SIDE",
  "UPPR",
]);

export const DIRECTIONALS: Readonly<Record<string, string>> = {
  E: "E",
  EAST: "E",
  N: "N",
  NE: "NE",
  NORTHEAST: "NE",
  NORTH: "N",
  NORTHWEST: "NW",
  NW: "NW",
  S: "S",
  SE: "SE",
  SOUTH: "S",
  SOUTHEAST: "SE",
  SOUTHWEST: "SW",
  SW: "SW",
  W: "W",
  WEST: "W",
};

export const STATE_ABBREVIATIONS = new Set([
  "AA",
  "AE",
  "AK",
  "AL",
  "AP",
  "AR",
  "AS",
  "AZ",
  "CA",
  "CO",
  "CT",
  "DC",
  "DE",
  "FL",
  "FM",
  "GA",
  "GU",
  "HI",
  "IA",
  "ID",
  "IL",
  "IN",
  "KS",
  "KY",
  "LA",
  "MA",
  "MD",
  "ME",
  "MH",
  "MI",
  "MN",
  "MO",
  "MP",
  "MS",
  "MT",
  "NC",
  "ND",
  "NE",
  "NH",
  "NJ",
  "NM",
  "NV",
  "NY",
  "OH",
  "OK",
  "OR",
  "PA",
  "PR",
  "PW",
  "RI",
  "SC",
  "SD",
  "TN",
  "TX",
  "UT",
  "VA",
  "VI",
  "VT",
  "WA",
  "WI",
  "WV",
  "WY",
]);

export const STATE_NAMES: Readonly<Record<string, string>> = {
  ALABAMA: "AL",
  ALASKA: "AK",
  "AMERICAN SAMOA": "AS",
  ARIZONA: "AZ",
  ARKANSAS: "AR",
  CALIFORNIA: "CA",
  COLORADO: "CO",
  CONNECTICUT: "CT",
  DELAWARE: "DE",
  "DISTRICT OF COLUMBIA": "DC",
  FLORIDA: "FL",
  "FEDERATED STATES OF MICRONESIA": "FM",
  GEORGIA: "GA",
  GUAM: "GU",
  HAWAII: "HI",
  IDAHO: "ID",
  ILLINOIS: "IL",
  INDIANA: "IN",
  IOWA: "IA",
  KANSAS: "KS",
  KENTUCKY: "KY",
  LOUISIANA: "LA",
  MAINE: "ME",
  "MARSHALL ISLANDS": "MH",
  MARYLAND: "MD",
  MASSACHUSETTS: "MA",
  MICHIGAN: "MI",
  MINNESOTA: "MN",
  MISSISSIPPI: "MS",
  MISSOURI: "MO",
  MONTANA: "MT",
  NEBRASKA: "NE",
  NEVADA: "NV",
  "NEW HAMPSHIRE": "NH",
  "NEW JERSEY": "NJ",
  "NEW MEXICO": "NM",
  "NEW YORK": "NY",
  "NORTH CAROLINA": "NC",
  "NORTH DAKOTA": "ND",
  "NORTHERN MARIANA ISLANDS": "MP",
  OHIO: "OH",
  OKLAHOMA: "OK",
  OREGON: "OR",
  PALAU: "PW",
  PENNSYLVANIA: "PA",
  "PUERTO RICO": "PR",
  "RHODE ISLAND": "RI",
  "SOUTH CAROLINA": "SC",
  "SOUTH DAKOTA": "SD",
  TENNESSEE: "TN",
  TEXAS: "TX",
  UTAH: "UT",
  VERMONT: "VT",
  "VIRGIN ISLANDS": "VI",
  VIRGINIA: "VA",
  WASHINGTON: "WA",
  "WEST VIRGINIA": "WV",
  WISCONSIN: "WI",
  WYOMING: "WY",
};
